# Generated by Django 3.2.5 on 2021-10-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(null=True)),
                ('layer_name', models.CharField(max_length=256, null=True)),
                ('readable_name', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('type', models.CharField(choices=[('WFS', 'WFS'), ('WMS', 'WMS'), ('WMST', 'WMST')], max_length=256)),
                ('parameters', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('service_url', models.TextField(null=True)),
                ('metadata_url', models.TextField(null=True)),
                ('leyend_url', models.TextField(null=True)),
                ('more_data_url', models.TextField(null=True)),
                ('copyright', models.TextField(null=True)),
                ('initial_time_range', models.DateField(blank=True, null=True)),
                ('final_time_range', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='twin_earth.category')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'db_table': 'layer',
            },
        ),
    ]
