# Generated by Django 3.2.5 on 2022-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_earth', '0003_layer_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
