# Generated by Django 3.2.5 on 2022-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_earth', '0004_layer_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
