# Generated by Django 3.2.5 on 2022-02-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin_earth', '0005_alter_layer_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.CharField(choices=[('WFS', 'WFS'), ('WMS', 'WMS'), ('WMST', 'WMST'), ('ARCGIS_IS', 'ArcGIS ImageServer')], max_length=256),
        ),
    ]
